name: Heroku Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'packages/server/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: jgfurlan2@gmail.com
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
