name: Heroku Server Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'packages/server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "christino-sgi"
          heroku_email: "jgfurlan2@gmail.com"
          usedocker: true
